[package]
name = "svdtools"
version = "0.1.0"
authors = ["MarcoIeni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.3"
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.18", features = ["serialize"] }
