[package]
name = "svdtools"
version = "0.1.0"
authors = ["MarcoIeni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt="0.3"
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.18", features = ["serialize"] }
svd-parser = { version = "0.10" , features = ["serde"] }
serde_yaml = "0.8"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.1"
